### ISSUE TITLE
Отрисовать макеты интерфейсов

### ISSUE THREAD

**Issue by avokado03** [avokado03/MobileList#3]
Спринт 1

**Comment by gora5624** [comment]
Жду макеты на согласование

**Comment by avokado03** [comment]
[Пленка_UI_Спринт_1.xlsx](https://github.com/avokado03/MobileList/files/5015497/_UI_._1.xlsx)


Егор, жду аппрува.

**Comment by gora5624** [comment]
Поправить текст. Заказ получаем не из Битрикс, а из 1С

**Comment by avokado03** [comment]
[Пленка_UI_Спринт_1.xlsx](https://github.com/avokado03/MobileList/files/5015505/_UI_._1.xlsx) 

Поменяла Битрикс на 1С

**Comment by gora5624** [comment]
Отлично, теперь нормально.
